repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: mixed-line-ending
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/myint/autoflake
    rev: v2.0.0
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
  - repo: https://github.com/dhruvmanila/remove-print-statements
    rev: v0.5.1
    hooks:
      - id: remove-print-statements
        args: ['--verbose']
