from enum import Enum
from external.database import db
from app.libs.models import BaseModel
from app.libs.helpers import UniqueIdMixin
from sqlalchemy.dialects.postgresql import JSONB


class RequestStatus(Enum):
    OPEN = "open"
    FULFILLED = "fulfilled"
    CLOSED = "closed"
    EXPIRED = "expired"


class RequestSource(Enum):
    """§7.4: a BuyerRequest is either posted by a buyer directly (the
    original, general-purpose use of this rail) or auto-generated by the
    rerouting engine when it genuinely exhausts its direct candidate
    lookup (app.fulfilment.rerouting) -- a wider, asynchronous net for
    sellers the keyword+category match didn't find. Distinguishing the
    two matters for UI (a buyer shouldn't see a system-generated request
    presented as if they personally posted it) and for accept_offer's
    behaviour (a REROUTE_ENGINE request's accepted offer must actually
    reserve stock and reopen fulfilment for the order item, not just flip
    the request to FULFILLED)."""

    BUYER = "buyer"
    REROUTE_ENGINE = "reroute_engine"


class BuyerRequest(BaseModel, UniqueIdMixin):
    __tablename__ = "buyer_requests"
    id_prefix = "REQ_"

    id = db.Column(db.String(12), primary_key=True, default=None)
    user_id = db.Column(db.String(12), db.ForeignKey("users.id"))
    title = db.Column(db.String(100), nullable=False)
    description = db.Column(db.Text, nullable=False)
    budget = db.Column(db.Float)
    status = db.Column(db.Enum(RequestStatus), default=RequestStatus.OPEN)
    request_metadata = db.Column(JSONB)  # For attributes, images etc
    expires_at = db.Column(db.DateTime)
    source = db.Column(
        db.Enum(RequestSource), default=RequestSource.BUYER, nullable=False
    )
    # Set only for a REROUTE_ENGINE request -- the OrderItem this request
    # exists to find a replacement seller for. Nullable: a buyer-posted
    # request isn't tied to any specific order.
    order_item_id = db.Column(
        db.Integer, db.ForeignKey("order_items.id"), nullable=True
    )
    # Set only for a REROUTE_ENGINE request -- rerouting is within-market
    # only (ADR §18.2), so responses need to be scoped the same way the
    # direct candidate lookup already is. Nullable for buyer-posted
    # requests, which aren't market-scoped at all.
    market_id = db.Column(db.Integer, db.ForeignKey("markets.id"), nullable=True)

    # Social features
    upvotes = db.Column(db.Integer, default=0)
    views = db.Column(db.Integer, default=0)

    # Relationships
    user = db.relationship("User", back_populates="requests")
    categories = db.relationship("RequestCategory", back_populates="request")
    # comments = db.relationship("RequestComment", back_populates="request")
    offers = db.relationship("SellerOffer", back_populates="request")
    images = db.relationship("RequestImage", back_populates="request")

    created_at = db.Column(db.DateTime, server_default=db.func.now())
    updated_at = db.Column(db.DateTime, onupdate=db.func.now())


class SellerOffer(BaseModel):
    __tablename__ = "seller_offers"

    id = db.Column(db.Integer, primary_key=True)
    request_id = db.Column(db.String(12), db.ForeignKey("buyer_requests.id"))
    seller_id = db.Column(db.Integer, db.ForeignKey("sellers.id"))
    product_id = db.Column(db.String(12), db.ForeignKey("products.id"), nullable=True)
    price = db.Column(db.Float)
    message = db.Column(db.Text)
    status = db.Column(db.String(20), default="pending")  # pending/accepted/rejected

    request = db.relationship("BuyerRequest", back_populates="offers")
    seller = db.relationship("Seller", back_populates="offers")
    product = db.relationship("Product")
