"""saved items

Revision ID: 4875f47262d6
Revises: 72bf175405d5
Create Date: 2026-09-02 08:41:20.561025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4875f47262d6'
down_revision = '72bf175405d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_items',
    sa.Column('user_id', sa.String(length=12), nullable=False),
    sa.Column('content_type', sa.Enum('POST', 'PRODUCT', name='saveditemtype'), nullable=False),
    sa.Column('content_id', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'content_type', 'content_id')
    )
    with op.batch_alter_table('saved_items', schema=None) as batch_op:
        batch_op.create_index('ix_saved_items_user_type', ['user_id', 'content_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_items', schema=None) as batch_op:
        batch_op.drop_index('ix_saved_items_user_type')

    op.drop_table('saved_items')
    # ### end Alembic commands ###
