"""content reports and user blocks

Revision ID: 60c8535881c4
Revises: e143139d1aef
Create Date: 2026-09-02 08:19:54.233813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c8535881c4'
down_revision = 'e143139d1aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_reports',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('reporter_id', sa.String(length=12), nullable=False),
    sa.Column('content_type', sa.Enum('POST', 'PRODUCT', 'COMMENT', 'CHAT_MESSAGE', 'USER', name='reportedcontenttype'), nullable=False),
    sa.Column('content_id', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Enum('SPAM', 'HARASSMENT', 'HATE_SPEECH', 'VIOLENCE', 'NUDITY', 'SCAM_OR_FRAUD', 'COUNTERFEIT', 'ILLEGAL_ITEM', 'OTHER', name='reportreason'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWING', 'ACTIONED', 'DISMISSED', name='reportstatus'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=12), nullable=True),
    sa.Column('resolution_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporter_id', 'content_type', 'content_id', name='uq_report_reporter_content')
    )
    with op.batch_alter_table('content_reports', schema=None) as batch_op:
        batch_op.create_index('ix_content_reports_content', ['content_type', 'content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_reports_status'), ['status'], unique=False)

    op.create_table('user_blocks',
    sa.Column('blocker_id', sa.String(length=12), nullable=False),
    sa.Column('blocked_id', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id')
    )
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_blocks_blocked_id'), ['blocked_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_blocks_blocked_id'))

    op.drop_table('user_blocks')
    with op.batch_alter_table('content_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_reports_status'))
        batch_op.drop_index(batch_op.f('ix_content_reports_reporter_id'))
        batch_op.drop_index('ix_content_reports_content')

    op.drop_table('content_reports')
    # ### end Alembic commands ###

    # Autogenerate creates these ENUM types implicitly via sa.Enum but never
    # drops them, so a downgrade left them behind and the next upgrade died on
    # `type "reportedcontenttype" already exists`. Only surfaces on a
    # downgrade-then-upgrade cycle, which is exactly what a rollback-and-retry
    # is.
    for enum_name in ("reportstatus", "reportreason", "reportedcontenttype"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
