"""feat(models): add base system for all reactions

Revision ID: 646619c3dd79
Revises: bbcd0cde4884
Create Date: 2025-07-24 09:56:20.181629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '646619c3dd79'
down_revision = 'bbcd0cde4884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_comment_reactions',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=False),
    sa.Column('reaction_type', sa.Enum('THUMBS_UP', 'THUMBS_DOWN', 'HEART', 'FIRE', 'STAR', 'MONEY', 'SHOPPING', 'CHECK', 'EYES', 'CLAP', 'ROCKET', 'SMILE', name='reactiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['post_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', 'reaction_type', name='uq_comment_reaction')
    )
    with op.batch_alter_table('post_comment_reactions', schema=None) as batch_op:
        batch_op.create_index('idx_comment_reaction_comment', ['comment_id'], unique=False)
        batch_op.create_index('idx_comment_reaction_type', ['reaction_type'], unique=False)
        batch_op.create_index('idx_comment_reaction_user', ['user_id'], unique=False)

    op.create_table('chat_message_reactions',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=False),
    sa.Column('reaction_type', sa.Enum('THUMBS_UP', 'THUMBS_DOWN', 'HEART', 'FIRE', 'STAR', 'MONEY', 'SHOPPING', 'CHECK', 'EYES', 'CLAP', 'ROCKET', 'SMILE', name='reactiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'reaction_type', name='uq_chat_message_reaction')
    )
    with op.batch_alter_table('chat_message_reactions', schema=None) as batch_op:
        batch_op.create_index('idx_chat_message_reaction_message', ['message_id'], unique=False)
        batch_op.create_index('idx_chat_message_reaction_type', ['reaction_type'], unique=False)
        batch_op.create_index('idx_chat_message_reaction_user', ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))

    with op.batch_alter_table('chat_message_reactions', schema=None) as batch_op:
        batch_op.drop_index('idx_chat_message_reaction_user')
        batch_op.drop_index('idx_chat_message_reaction_type')
        batch_op.drop_index('idx_chat_message_reaction_message')

    op.drop_table('chat_message_reactions')
    with op.batch_alter_table('post_comment_reactions', schema=None) as batch_op:
        batch_op.drop_index('idx_comment_reaction_user')
        batch_op.drop_index('idx_comment_reaction_type')
        batch_op.drop_index('idx_comment_reaction_comment')

    op.drop_table('post_comment_reactions')
    # ### end Alembic commands ###
