"""feat: markt v3.0 spec schema (markets, delivery runs, fulfilment allocations, order events, admin flag, and related columns)

Revision ID: 72bf175405d5
Revises: f2a3b4c5d6e7
Create Date: 2026-08-30 01:31:08.617330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '72bf175405d5'
down_revision = 'f2a3b4c5d6e7'
branch_labels = None
depends_on = None


def _column_exists(table: str, column: str) -> bool:
    return column in {
        col["name"] for col in inspect(op.get_bind()).get_columns(table)
    }


def _index_exists(table: str, index: str) -> bool:
    return index in {
        ix["name"] for ix in inspect(op.get_bind()).get_indexes(table)
    }


def _fk_exists(table: str, fk: str) -> bool:
    return fk in {
        f["name"] for f in inspect(op.get_bind()).get_foreign_keys(table)
    }


def _fk_on_column_exists(table: str, column: str) -> bool:
    return any(
        column in fk["constrained_columns"]
        for fk in inspect(op.get_bind()).get_foreign_keys(table)
    )


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # AssignmentStatus.FAILED (10.7, rider mid-run failure/reassignment)
    # was added to the existing `assignmentstatus` Postgres enum type
    # (shared between the pre-existing single-order
    # delivery_order_assignments.status and the new
    # delivery_run_assignments.status below) with no migration ever
    # capturing it either -- same class of gap as everything else in
    # this migration, just on a type instead of a table/column.
    # IF NOT EXISTS makes this safe to run against an environment where
    # it was somehow already added by hand.
    op.execute("ALTER TYPE assignmentstatus ADD VALUE IF NOT EXISTS 'FAILED'")

    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=110), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=110), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('category_confidence_priors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('prior_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id')
    )
    op.create_table('delivery_runs',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CUTOFF_REACHED', 'PLANNING', 'RIDER_ASSIGNMENT', 'RIDER_ACCEPTED', 'PICKUP_IN_PROGRESS', 'DELIVERY_IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'RIDER_FAILED', 'PARTIALLY_COMPLETED', name='deliveryrunstatus'), nullable=False),
    sa.Column('max_packages', sa.Integer(), nullable=False),
    sa.Column('max_weight_grams', sa.Integer(), nullable=False),
    sa.Column('cutoff_at', sa.DateTime(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('price_per_order', sa.Float(), nullable=True),
    sa.Column('surge_multiplier', sa.Float(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_run_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_run_id', sa.String(length=12), nullable=False),
    sa.Column('delivery_user_id', sa.String(length=12), nullable=False),
    sa.Column('status', postgresql.ENUM('ASSIGNED', 'ACCEPTED', 'REJECTED', 'FAILED', name='assignmentstatus', create_type=False), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_run_id'], ['delivery_runs.id'], ),
    sa.ForeignKeyConstraint(['delivery_user_id'], ['delivery_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_run_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_run_id', sa.String(length=12), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ARRIVED', 'PICKED_UP', name='deliveryrunstopstatus'), nullable=False),
    sa.Column('arrived_at', sa.DateTime(), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_run_id'], ['delivery_runs.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_run_id', 'seller_id', name='uq_delivery_run_stop_seller')
    )
    op.create_table('seller_reliability_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('acceptance_rate_component', sa.Float(), nullable=False),
    sa.Column('response_rate_component', sa.Float(), nullable=False),
    sa.Column('fulfilment_rate_component', sa.Float(), nullable=False),
    sa.Column('inventory_accuracy_component', sa.Float(), nullable=False),
    sa.Column('response_time_component', sa.Float(), nullable=False),
    sa.Column('cancellation_penalty', sa.Float(), nullable=False),
    sa.Column('gaming_flagged', sa.Boolean(), nullable=False),
    sa.Column('score_version', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id')
    )
    op.create_table('delivery_failures',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('delivery_run_id', sa.String(length=12), nullable=True),
    sa.Column('order_id', sa.String(length=12), nullable=False),
    sa.Column('reason', sa.Enum('BUYER_UNAVAILABLE', 'BAD_ADDRESS', 'BUYER_REFUSED', name='deliveryfailurereason'), nullable=False),
    sa.Column('reported_by_delivery_user_id', sa.String(length=12), nullable=True),
    sa.Column('reported_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('report_notes', sa.Text(), nullable=True),
    sa.Column('is_perishable', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.Enum('PENDING', 'RESOLVED', 'COMPLETED', name='deliveryfailureoutcome'), nullable=False),
    sa.Column('recovery_action', sa.Enum('REDELIVERY', 'RETURN_TO_SELLER', 'DISPOSE', name='deliveryrecoveryaction'), nullable=True),
    sa.Column('cost_bearer', sa.Enum('BUYER', 'SELLER', 'MARKT', name='deliverycostbearer'), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_run_id'], ['delivery_runs.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['reported_by_delivery_user_id'], ['delivery_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_run_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_run_id', sa.String(length=12), nullable=False),
    sa.Column('order_id', sa.String(length=12), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('wait_choice', sa.Enum('PENDING', 'WAIT', 'PAY_NOW', name='deliveryrunwaitchoice'), nullable=False),
    sa.Column('fallback_consent', sa.Boolean(), nullable=False),
    sa.Column('notified_thin_volume_at', sa.DateTime(), nullable=True),
    sa.Column('pod_status', sa.Enum('PENDING', 'QR_ISSUED', 'DELIVERED', name='deliveryrunorderpodstatus'), nullable=False),
    sa.Column('qr_code', sa.String(length=64), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_run_id'], ['delivery_runs.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('inventory_confidence_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=12), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('recency_component', sa.Float(), nullable=False),
    sa.Column('accuracy_component', sa.Float(), nullable=False),
    sa.Column('fulfilment_component', sa.Float(), nullable=False),
    sa.Column('activity_component', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('product_handling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=12), nullable=False),
    sa.Column('handling_class', sa.Enum('STANDARD', 'FRAGILE', 'PERISHABLE', 'TEMPERATURE_CONTROLLED', name='handlingclass'), nullable=False),
    sa.Column('max_transit_minutes', sa.Integer(), nullable=True),
    sa.Column('max_dwell_minutes', sa.Integer(), nullable=True),
    sa.Column('temperature_requirement', sa.String(length=50), nullable=True),
    sa.Column('fragile', sa.Boolean(), nullable=False),
    sa.Column('orientation_requirement', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('inventory_reservations',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('product_id', sa.String(length=12), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=12), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('needs_verification', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'HELD', 'CONFIRMED', 'CONSUMED', 'EXPIRED', 'RELEASED', name='inventory_reservations_status'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fulfilment_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=12), nullable=True),
    sa.Column('reservation_id', sa.String(length=12), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AWAITING_SELLER', 'ACCEPTED', 'DECLINED', 'TIMEOUT', 'REROUTING', 'PREPARING', 'UNFULFILLED', 'AWAITING_BUYER_APPROVAL', 'BUYER_REJECTED', 'CANCELLED_BY_SELLER', name='fulfilmentallocationstatus'), nullable=False),
    sa.Column('seller_response_deadline', sa.DateTime(), nullable=False),
    sa.Column('buyer_response_deadline', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['inventory_reservations.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=12), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('ORDER_CREATED', 'ORDER_CANCELLED', 'ITEM_ALLOCATED', 'ITEM_ACCEPTED', 'ITEM_DECLINED', 'ITEM_TIMED_OUT', 'ITEM_CANCELLED_BY_SELLER', 'ITEM_REROUTED', 'ITEM_UNFULFILLED', 'ITEM_ESCALATED', 'ITEM_SUBSTITUTION_PENDING', 'ITEM_SUBSTITUTION_APPROVED', 'ITEM_SUBSTITUTION_REJECTED', 'ITEM_REFUNDED', 'ITEM_DELIVERED', 'ITEM_DELIVERY_FAILED', name='ordereventtype'), nullable=False),
    sa.Column('actor_type', sa.Enum('BUYER', 'SELLER', 'RIDER', 'SYSTEM', name='actortype'), nullable=False),
    sa.Column('actor_id', sa.String(length=20), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # Enum types referenced only inside ADD COLUMN (batch_alter_table)
    # below, not inside a CREATE TABLE -- SQLAlchemy only auto-creates a
    # Postgres enum type as a side effect of table creation, so these
    # need an explicit create() or ADD COLUMN fails with "type does not
    # exist" (same pattern already established in this repo's own
    # b7c8d9e0f1a2/d9e0f1a2b3c4 idempotent-enum fix).
    sa.Enum('BUYER', 'REROUTE_ENGINE', name='requestsource').create(op.get_bind(), checkfirst=True)
    sa.Enum('AUTO', 'ASK', 'SELLER_ONLY', name='fulfilmentpreference').create(op.get_bind(), checkfirst=True)
    sa.Enum('UNVERIFIED', 'VERIFIED', 'FLAGGED', name='marketverificationstatus').create(op.get_bind(), checkfirst=True)

    # Every block below is guarded the same way as posts/users above --
    # this server has its own independent drift (columns added by hand
    # outside the migration chain), discovered incrementally via
    # migration_err.md. Guarding all of it up front rather than fixing
    # one failure at a time against the same server.
    with op.batch_alter_table('buyer_requests', schema=None) as batch_op:
        if not _column_exists('buyer_requests', 'source'):
            batch_op.add_column(sa.Column('source', sa.Enum('BUYER', 'REROUTE_ENGINE', name='requestsource'), nullable=False, server_default=sa.text("'BUYER'")))
            batch_op.alter_column('source', server_default=None)
        if not _column_exists('buyer_requests', 'order_item_id'):
            batch_op.add_column(sa.Column('order_item_id', sa.Integer(), nullable=True))
        if not _column_exists('buyer_requests', 'market_id'):
            batch_op.add_column(sa.Column('market_id', sa.Integer(), nullable=True))
        if not _fk_on_column_exists('buyer_requests', 'market_id'):
            batch_op.create_foreign_key(None, 'markets', ['market_id'], ['id'])
        if not _fk_on_column_exists('buyer_requests', 'order_item_id'):
            batch_op.create_foreign_key(None, 'order_items', ['order_item_id'], ['id'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        if not _column_exists('order_items', 'delivered_at'):
            batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        if not _column_exists('order_items', 'settled_at'):
            batch_op.add_column(sa.Column('settled_at', sa.DateTime(), nullable=True))
        if not _column_exists('order_items', 'fulfilment_preference'):
            batch_op.add_column(sa.Column('fulfilment_preference', sa.Enum('AUTO', 'ASK', 'SELLER_ONLY', name='fulfilmentpreference'), nullable=False, server_default=sa.text("'AUTO'")))
            batch_op.alter_column('fulfilment_preference', server_default=None)
        if not _column_exists('order_items', 'fulfilled_quantity'):
            batch_op.add_column(sa.Column('fulfilled_quantity', sa.Integer(), nullable=False, server_default=sa.text('0')))
            batch_op.alter_column('fulfilled_quantity', server_default=None)
        if not _column_exists('order_items', 'allow_partial_quantity'):
            batch_op.add_column(sa.Column('allow_partial_quantity', sa.Boolean(), nullable=False, server_default=sa.text('true')))
            batch_op.alter_column('allow_partial_quantity', server_default=None)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        if not _column_exists('orders', 'service_fee'):
            batch_op.add_column(sa.Column('service_fee', sa.Float(), nullable=True))
        if not _column_exists('orders', 'reliability_fee_opted_in'):
            batch_op.add_column(sa.Column('reliability_fee_opted_in', sa.Boolean(), nullable=False, server_default=sa.text('false')))
            batch_op.alter_column('reliability_fee_opted_in', server_default=None)
        if not _column_exists('orders', 'reliability_fee_estimate'):
            batch_op.add_column(sa.Column('reliability_fee_estimate', sa.Float(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        if not _column_exists('payments', 'buyer_id'):
            batch_op.add_column(sa.Column('buyer_id', sa.Integer(), nullable=True))
        if not _column_exists('payments', 'pending_checkout_data'):
            batch_op.add_column(sa.Column('pending_checkout_data', sa.JSON(), nullable=True))
        if not _fk_on_column_exists('payments', 'buyer_id'):
            batch_op.create_foreign_key(None, 'buyers', ['buyer_id'], ['id'])

    # posts cleanup made defensive, not assumed -- found via the test
    # server's own upgrade log (migration_err.md): that environment's
    # `posts` table doesn't have `idx_seller_posts` even though the
    # column/FK it indexes are still there, unlike every DB this
    # migration was checked against before (local markt_db, the
    # disposable verification DB) -- same class of independent drift as
    # markt_db's own delivery_users.id mismatch. Each step now checks
    # for its own precondition instead of assuming the environment
    # matches what was verified elsewhere.
    with op.batch_alter_table('posts', schema=None) as batch_op:
        if _index_exists('posts', 'idx_seller_posts'):
            batch_op.drop_index('idx_seller_posts')
        if not _index_exists('posts', 'idx_user_posts'):
            batch_op.create_index('idx_user_posts', ['user_id', 'created_at'], unique=False)
        if _fk_exists('posts', 'posts_seller_id_fkey'):
            batch_op.drop_constraint('posts_seller_id_fkey', type_='foreignkey')
        if _column_exists('posts', 'seller_id'):
            batch_op.drop_column('seller_id')

    # seller_offers.status: real bug fix (Phase 13/escalation work) --
    # this column was a plain VARCHAR(20), but create_offer() wrote the
    # literal lowercase string "pending" while accept_offer/reject_offer/
    # withdraw_offer all compared against the OfferStatus *enum member*,
    # which is never == a plain string -- so real offer accept/reject/
    # withdraw calls always failed in production (see the model's own
    # comment on SellerOffer.status). Any existing row can therefore only
    # ever hold "pending" (accept/reject/withdraw never successfully
    # wrote anything else) -- explicit USING clause maps that one known
    # value, and anything unexpected is treated as PENDING too rather
    # than aborting the migration outright, since the safe fallback for
    # "we don't know what this string actually meant" is the same status
    # every real offer has always effectively been stuck at.
    offerstatus_enum = sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='offerstatus')
    offerstatus_enum.create(op.get_bind(), checkfirst=True)
    op.execute(
        "ALTER TABLE seller_offers ALTER COLUMN status TYPE offerstatus "
        "USING (CASE UPPER(status) "
        "WHEN 'PENDING' THEN 'PENDING' "
        "WHEN 'ACCEPTED' THEN 'ACCEPTED' "
        "WHEN 'REJECTED' THEN 'REJECTED' "
        "WHEN 'WITHDRAWN' THEN 'WITHDRAWN' "
        "ELSE 'PENDING' END)::offerstatus"
    )
    op.execute("ALTER TABLE seller_offers ALTER COLUMN status SET NOT NULL")
    op.execute("ALTER TABLE seller_offers ALTER COLUMN status SET DEFAULT 'PENDING'::offerstatus")

    with op.batch_alter_table('sellers', schema=None) as batch_op:
        if not _column_exists('sellers', 'market_id'):
            batch_op.add_column(sa.Column('market_id', sa.Integer(), nullable=True))
        if not _column_exists('sellers', 'shop_address'):
            batch_op.add_column(sa.Column('shop_address', sa.JSON(), nullable=True))
        if not _column_exists('sellers', 'shop_latitude'):
            batch_op.add_column(sa.Column('shop_latitude', sa.Float(), nullable=True))
        if not _column_exists('sellers', 'shop_longitude'):
            batch_op.add_column(sa.Column('shop_longitude', sa.Float(), nullable=True))
        if not _column_exists('sellers', 'market_verification_status'):
            batch_op.add_column(sa.Column('market_verification_status', sa.Enum('UNVERIFIED', 'VERIFIED', 'FLAGGED', name='marketverificationstatus'), nullable=False, server_default=sa.text("'UNVERIFIED'")))
            batch_op.alter_column('market_verification_status', server_default=None)
        if not _fk_on_column_exists('sellers', 'market_id'):
            batch_op.create_foreign_key(None, 'markets', ['market_id'], ['id'])

    with op.batch_alter_table('shipping_addresses', schema=None) as batch_op:
        if not _column_exists('shipping_addresses', 'area_id'):
            batch_op.add_column(sa.Column('area_id', sa.Integer(), nullable=True))
        if not _fk_on_column_exists('shipping_addresses', 'area_id'):
            batch_op.create_foreign_key(None, 'areas', ['area_id'], ['id'])

    # is_admin/email_verified made defensive too -- this server already
    # had `email_verified` (added by hand at some point, outside any
    # migration) even though `is_admin` did not, same independent-drift
    # pattern as the posts index above (see migration_err.md).
    with op.batch_alter_table('users', schema=None) as batch_op:
        if not _column_exists('users', 'is_admin'):
            batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')))
            batch_op.alter_column('is_admin', server_default=None)
        if not _column_exists('users', 'email_verified'):
            batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('shipping_addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('area_id')

    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('market_verification_status')
        batch_op.drop_column('shop_longitude')
        batch_op.drop_column('shop_latitude')
        batch_op.drop_column('shop_address')
        batch_op.drop_column('market_id')

    with op.batch_alter_table('seller_offers', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='offerstatus'),
               type_=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('posts_seller_id_fkey', 'sellers', ['seller_id'], ['id'])
        batch_op.drop_index('idx_user_posts')
        batch_op.create_index('idx_seller_posts', ['seller_id', 'created_at'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pending_checkout_data')
        batch_op.drop_column('buyer_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('reliability_fee_estimate')
        batch_op.drop_column('reliability_fee_opted_in')
        batch_op.drop_column('service_fee')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('allow_partial_quantity')
        batch_op.drop_column('fulfilled_quantity')
        batch_op.drop_column('fulfilment_preference')
        batch_op.drop_column('settled_at')
        batch_op.drop_column('delivered_at')

    with op.batch_alter_table('buyer_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('market_id')
        batch_op.drop_column('order_item_id')
        batch_op.drop_column('source')

    op.drop_table('order_events')
    op.drop_table('fulfilment_allocations')
    op.drop_table('inventory_reservations')
    op.drop_table('product_handling')
    op.drop_table('inventory_confidence_scores')
    op.drop_table('delivery_run_orders')
    op.drop_table('delivery_failures')
    op.drop_table('seller_reliability_scores')
    op.drop_table('delivery_run_stops')
    op.drop_table('delivery_run_assignments')
    op.drop_table('delivery_runs')
    op.drop_table('category_confidence_priors')
    op.drop_table('markets')
    op.drop_table('areas')
    # ### end Alembic commands ###
