"""fix(categories): standardize category relationships to many-to-many

Revision ID: bbcd0cde4884
Revises: fe266f0e8b81
Create Date: 2025-07-18 08:00:23.975987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbcd0cde4884'
down_revision = 'fe266f0e8b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('niche_categories',
    sa.Column('niche_id', sa.String(length=12), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.PrimaryKeyConstraint('niche_id', 'category_id')
    )
    op.create_table('request_categories',
    sa.Column('request_id', sa.String(length=12), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['buyer_requests.id'], ),
    sa.PrimaryKeyConstraint('request_id', 'category_id')
    )
    op.create_table('seller_categories',
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('seller_id', 'category_id')
    )
    op.create_table('post_categories',
    sa.Column('post_id', sa.String(length=12), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'category_id')
    )
    with op.batch_alter_table('buyer_requests', schema=None) as batch_op:
        batch_op.drop_constraint('buyer_requests_category_id_fkey', type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('niches', schema=None) as batch_op:
        batch_op.drop_index('idx_niche_category')
        batch_op.drop_constraint('niches_category_id_fkey', type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posts_category_id', type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_posts_category_id', 'categories', ['category_id'], ['id'])

    with op.batch_alter_table('niches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('niches_category_id_fkey', 'categories', ['category_id'], ['id'])
        batch_op.create_index('idx_niche_category', ['category_id'], unique=False)

    with op.batch_alter_table('buyer_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('buyer_requests_category_id_fkey', 'categories', ['category_id'], ['id'])

    op.drop_table('post_categories')
    op.drop_table('seller_categories')
    op.drop_table('request_categories')
    op.drop_table('niche_categories')
    # ### end Alembic commands ###
