"""added tables for delivery tracking, store and auth

Revision ID: d49181fc51b4
Revises: 
Create Date: 2026-02-25 00:59:06.597659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd49181fc51b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=60), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('category_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('niches',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MODERATED', 'ARCHIVED', name='nichestatus'), nullable=True),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', 'RESTRICTED', name='nichevisibility'), nullable=True),
    sa.Column('allow_buyer_posts', sa.Boolean(), nullable=True),
    sa.Column('allow_seller_posts', sa.Boolean(), nullable=True),
    sa.Column('require_approval', sa.Boolean(), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('niches', schema=None) as batch_op:
        batch_op.create_index('idx_niche_slug', ['slug'], unique=False)
        batch_op.create_index('idx_niche_status', ['status'], unique=False)
        batch_op.create_index('idx_niche_visibility', ['visibility'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('is_buyer', sa.Boolean(), nullable=True),
    sa.Column('is_seller', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('buyer_requests',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'FULFILLED', 'CLOSED', 'EXPIRED', name='requeststatus'), nullable=True),
    sa.Column('request_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=True),
    sa.Column('buyername', sa.String(length=50), nullable=True),
    sa.Column('shipping_address', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.String(length=12), nullable=False),
    sa.Column('followee_id', sa.String(length=12), nullable=False),
    sa.Column('follow_type', sa.Enum('CUSTOMER', 'PEER', name='followtype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followee_id')
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index('idx_followee_follower', ['followee_id', 'follower_id'], unique=False)

    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=True),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'DOCUMENT', 'AUDIO', name='mediatype'), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.String(length=12), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('background_removed', sa.Boolean(), nullable=True),
    sa.Column('compression_quality', sa.Integer(), nullable=True),
    sa.Column('exif_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_table('niche_categories',
    sa.Column('niche_id', sa.String(length=12), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.PrimaryKeyConstraint('niche_id', 'category_id')
    )
    op.create_table('niche_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niche_id', sa.String(length=12), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=False),
    sa.Column('role', sa.Enum('MEMBER', 'MODERATOR', 'ADMIN', 'OWNER', name='nichemembershiprole'), nullable=True),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('invited_by', sa.String(length=12), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('banned_until', sa.DateTime(), nullable=True),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('niche_id', 'user_id', name='uq_niche_membership')
    )
    with op.batch_alter_table('niche_memberships', schema=None) as batch_op:
        batch_op.create_index('idx_niche_membership_active', ['is_active'], unique=False)
        batch_op.create_index('idx_niche_membership_role', ['role'], unique=False)
        batch_op.create_index('idx_niche_membership_user', ['user_id'], unique=False)

    op.create_table('niche_moderation_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niche_id', sa.String(length=12), nullable=False),
    sa.Column('moderator_id', sa.String(length=12), nullable=False),
    sa.Column('target_user_id', sa.String(length=12), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=12), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('niche_moderation_actions', schema=None) as batch_op:
        batch_op.create_index('idx_moderation_active', ['is_active'], unique=False)
        batch_op.create_index('idx_moderation_niche', ['niche_id'], unique=False)
        batch_op.create_index('idx_moderation_target', ['target_user_id'], unique=False)
        batch_op.create_index('idx_moderation_type', ['action_type'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=False),
    sa.Column('type', sa.Enum('POST_LIKE', 'POST_COMMENT', 'NEW_FOLLOWER', 'PRODUCT_REVIEW', 'REVIEW_UPVOTE', 'ORDER_UPDATE', 'SHIPMENT_UPDATE', 'PROMOTIONAL', 'SYSTEM_ALERT', 'REQUEST_OFFER', 'OFFER_ACCEPTED', 'OFFER_REJECTED', 'OFFER_WITHDRAWN', 'REQUEST_CLOSED', 'REQUEST_STATUS_CHANGE', 'REQUEST_EXPIRED', 'CART_ITEM_ADDED', 'ORDER_PLACED', 'PAYMENT_SUCCESS', 'PAYMENT_FAILED', 'NICHE_INVITATION', 'NICHE_POST_APPROVED', 'NICHE_POST_REJECTED', 'MODERATION_ACTION', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_seen', sa.Boolean(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=12), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notification_user_type', ['user_id', 'type'], unique=False)
        batch_op.create_index('idx_notification_user_unread', ['user_id', 'is_read'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', 'DELETED', name='poststatus'), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index('idx_post_search', [sa.text("to_tsvector('english', caption)")], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_user_posts', ['user_id', 'created_at'], unique=False)

    op.create_table('sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=True),
    sa.Column('shop_name', sa.String(length=100), nullable=True),
    sa.Column('shop_slug', sa.String(length=110), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('policies', sa.JSON(), nullable=True),
    sa.Column('total_rating', sa.Integer(), nullable=True),
    sa.Column('total_raters', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED', 'SUSPENDED', name='sellerverificationstatus'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_slug')
    )
    op.create_table('user_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('house_number', sa.String(length=20), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.String(length=12), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('push_notifications', sa.Boolean(), nullable=True),
    sa.Column('sms_notifications', sa.Boolean(), nullable=True),
    sa.Column('privacy_public_profile', sa.Boolean(), nullable=True),
    sa.Column('preferred_language', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('coupon_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('variant_type', sa.Enum('ORIGINAL', 'THUMBNAIL', 'SMALL', 'MEDIUM', 'LARGE', 'MOBILE', 'TABLET', 'DESKTOP', 'SOCIAL_SQUARE', 'SOCIAL_STORY', 'SOCIAL_POST', name='mediavarianttype'), nullable=True),
    sa.Column('storage_key', sa.String(length=255), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('niche_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niche_id', sa.String(length=12), nullable=False),
    sa.Column('post_id', sa.String(length=12), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', 'DELETED', name='poststatus'), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('moderated_by', sa.String(length=12), nullable=True),
    sa.Column('moderated_at', sa.DateTime(), nullable=True),
    sa.Column('niche_likes', sa.Integer(), nullable=True),
    sa.Column('niche_comments', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['moderated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('niche_id', 'post_id', name='uq_niche_post')
    )
    with op.batch_alter_table('niche_posts', schema=None) as batch_op:
        batch_op.create_index('idx_niche_post_featured', ['is_featured'], unique=False)
        batch_op.create_index('idx_niche_post_pinned', ['is_pinned'], unique=False)
        batch_op.create_index('idx_niche_post_status', ['status'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('order_number', sa.String(length=21), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('shipping_fee', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'READY_FOR_DELIVERY', 'PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', 'FAILED', name='orderstatus'), nullable=True),
    sa.Column('billing_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('customer_note', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('order_number')
    )
    op.create_table('post_categories',
    sa.Column('post_id', sa.String(length=12), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'category_id')
    )
    op.create_table('post_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=True),
    sa.Column('post_id', sa.String(length=12), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['post_comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_likes',
    sa.Column('user_id', sa.String(length=12), nullable=False),
    sa.Column('post_id', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('compare_at_price', sa.Float(), nullable=True),
    sa.Column('cost_per_item', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('product_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DRAFT', 'ARCHIVED', 'OUT_OF_STOCK', 'DELETED', name='products_status'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('request_categories',
    sa.Column('request_id', sa.String(length=12), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['buyer_requests.id'], ),
    sa.PrimaryKeyConstraint('request_id', 'category_id')
    )
    op.create_table('request_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=12), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['buyer_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller_categories',
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('seller_id', 'category_id')
    )
    op.create_table('social_media_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=12), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('post_type', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=20), nullable=True),
    sa.Column('optimized_for_platform', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('payment_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.String(length=12), nullable=True),
    sa.Column('seller_id', sa.String(length=12), nullable=True),
    sa.Column('product_id', sa.String(length=12), nullable=True),
    sa.Column('request_id', sa.String(length=12), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('unread_count_buyer', sa.Integer(), nullable=True),
    sa.Column('unread_count_seller', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['buyer_requests.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('order_id', sa.String(length=12), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('method', sa.Enum('CARD', 'BANK_TRANSFER', 'MOBILE_MONEY', 'WALLET', name='paymentmethod'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED', name='paymentstatus'), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_response', sa.JSON(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('post_comment_reactions',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=False),
    sa.Column('reaction_type', sa.Enum('THUMBS_UP', 'THUMBS_DOWN', 'HEART', 'FIRE', 'STAR', 'MONEY', 'SHOPPING', 'CHECK', 'EYES', 'CLAP', 'ROCKET', 'SMILE', name='reactiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['post_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', 'reaction_type', name='uq_comment_reaction')
    )
    with op.batch_alter_table('post_comment_reactions', schema=None) as batch_op:
        batch_op.create_index('idx_comment_reaction_comment', ['comment_id'], unique=False)
        batch_op.create_index('idx_comment_reaction_type', ['reaction_type'], unique=False)
        batch_op.create_index('idx_comment_reaction_user', ['user_id'], unique=False)

    op.create_table('post_products',
    sa.Column('post_id', sa.String(length=12), nullable=False),
    sa.Column('product_id', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'product_id')
    )
    op.create_table('product_categories',
    sa.Column('product_id', sa.String(length=12), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'category_id')
    )
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=12), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=True),
    sa.Column('product_id', sa.String(length=12), nullable=True),
    sa.Column('order_id', sa.String(length=12), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_tags',
    sa.Column('product_id', sa.String(length=12), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'tag_id')
    )
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=True),
    sa.Column('product_id', sa.String(length=12), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=12), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.String(length=12), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['buyer_requests.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=12), nullable=True),
    sa.Column('carrier', sa.String(length=50), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('tracking_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipping_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=12), nullable=True),
    sa.Column('recipient_name', sa.String(length=100), nullable=True),
    sa.Column('street_address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.String(length=12), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('product_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.String(length=12), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('message_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=12), nullable=True),
    sa.Column('product_id', sa.String(length=12), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='order_items_status'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=12), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.String(length=12), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('minimum_order_amount', sa.Float(), nullable=True),
    sa.Column('maximum_discount_amount', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by_id', sa.String(length=12), nullable=False),
    sa.Column('offered_to_id', sa.String(length=12), nullable=False),
    sa.Column('discount_message', sa.Text(), nullable=True),
    sa.Column('discount_code', sa.String(length=50), nullable=True),
    sa.Column('discount_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['offered_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message_reactions',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=False),
    sa.Column('reaction_type', sa.Enum('THUMBS_UP', 'THUMBS_DOWN', 'HEART', 'FIRE', 'STAR', 'MONEY', 'SHOPPING', 'CHECK', 'EYES', 'CLAP', 'ROCKET', 'SMILE', name='reactiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'reaction_type', name='uq_chat_message_reaction')
    )
    with op.batch_alter_table('chat_message_reactions', schema=None) as batch_op:
        batch_op.create_index('idx_chat_message_reaction_message', ['message_id'], unique=False)
        batch_op.create_index('idx_chat_message_reaction_type', ['reaction_type'], unique=False)
        batch_op.create_index('idx_chat_message_reaction_user', ['user_id'], unique=False)

    op.create_table('chat_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.String(length=12), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_last_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='When this location was recorded - use DESC index for getting latest',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('accuracy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='GPS accuracy in meters (smaller is better)',
               existing_nullable=True)
        batch_op.drop_index('idx_delivery_last_locations_delivery_user_id')
        batch_op.drop_index('idx_delivery_last_locations_geo')
        batch_op.drop_index('idx_delivery_last_locations_timestamp')
        batch_op.drop_constraint('fk_delivery_user_location', type_='foreignkey')
        batch_op.create_foreign_key(None, 'delivery_users', ['delivery_user_id'], ['id'])
        batch_op.drop_table_comment(
        'delivery_last_locations',
        existing_comment='Stores the most recent GPS location of each delivery partner for tracking',
        schema=None
    )

    with op.batch_alter_table('delivery_order_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('assignment_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='UUID for idempotent assignment creation (prevents duplicate assignments)',
               existing_nullable=False)
        batch_op.alter_column('assigned_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('ASSIGNED', 'ACCEPTED', 'REJECTED', name='assignment_status'),
               type_=sa.Enum('ASSIGNED', 'ACCEPTED', 'REJECTED', name='assignmentstatus'),
               comment=None,
               existing_comment='Assignment status: ASSIGNED (awaiting response), ACCEPTED (partner accepted), REJECTED (partner declined)',
               existing_nullable=False)
        batch_op.alter_column('logistical_status',
               existing_type=postgresql.ENUM('ARRIVED_PICKUP', 'PICKED_UP', 'EN_ROUTE_TO_DROPOFF', 'DELIVERED_PENDING_QR', name='logistical_status'),
               type_=sa.Enum('ARRIVED_PICKUP', 'PICKED_UP', 'EN_ROUTE_TO_DROPOFF', 'DELIVERED_PENDING_QR', name='logisticalstatus'),
               comment=None,
               existing_comment='Delivery progress: ARRIVED_PICKUP -> PICKED_UP -> EN_ROUTE_TO_DROPOFF -> DELIVERED_PENDING_QR',
               existing_nullable=True)
        batch_op.alter_column('escrow_qr_code',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='QR code scanned by buyer to release escrow payment after delivery confirmation',
               existing_nullable=False)
        batch_op.drop_index('idx_delivery_order_assignments_assigned_at')
        batch_op.drop_index('idx_delivery_order_assignments_assignment_id')
        batch_op.drop_index('idx_delivery_order_assignments_delivery_user_id')
        batch_op.drop_index('idx_delivery_order_assignments_logistical_status')
        batch_op.drop_index('idx_delivery_order_assignments_order_id')
        batch_op.drop_index('idx_delivery_order_assignments_room_id')
        batch_op.drop_index('idx_delivery_order_assignments_status')
        batch_op.drop_constraint('fk_location_room_assignment', type_='foreignkey')
        batch_op.drop_constraint('fk_delivery_user_assignment', type_='foreignkey')
        batch_op.create_foreign_key(None, 'location_update_rooms', ['room_id'], ['room_id'])
        batch_op.create_foreign_key(None, 'delivery_users', ['delivery_user_id'], ['id'])
        batch_op.drop_table_comment(
        'delivery_order_assignments',
        existing_comment='Links orders to delivery partners and tracks the status of each assignment through the delivery lifecycle',
        schema=None
    )

    with op.batch_alter_table('delivery_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Unique identifier for delivery partner',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=15),
               comment=None,
               existing_comment='Used for OTP authentication during login',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', name='delivery_status'),
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='deliverystatus'),
               comment=None,
               existing_comment='Current status: ACTIVE for available, INACTIVE for disabled, SUSPENDED for temporary ban',
               existing_nullable=False)
        batch_op.alter_column('vehicle_type',
               existing_type=postgresql.ENUM('BIKE', 'CAR', 'VAN', 'TRUCK', name='delivery_vehicle_type'),
               type_=sa.Enum('BIKE', 'CAR', 'VAN', 'TRUCK', name='deliveryvehicletype'),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('rating',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_constraint('delivery_users_email_key', type_='unique')
        batch_op.drop_constraint('delivery_users_phone_number_key', type_='unique')
        batch_op.drop_index('idx_delivery_users_created_at')
        batch_op.drop_index('idx_delivery_users_email')
        batch_op.drop_index('idx_delivery_users_phone_number')
        batch_op.drop_index('idx_delivery_users_status')
        batch_op.drop_table_comment(
        'delivery_users',
        existing_comment='Stores delivery partner information and status',
        schema=None
    )

    with op.batch_alter_table('location_update_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('room_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Socket.io room identifier (UUID format)',
               existing_nullable=False)
        batch_op.alter_column('delivery_user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Delivery partner assigned to this room (optional, can be NULL)',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('idx_location_update_rooms_created_at')
        batch_op.drop_index('idx_location_update_rooms_delivery_user_id')
        batch_op.drop_index('idx_location_update_rooms_room_id')
        batch_op.drop_constraint('fk_delivery_user_rooms', type_='foreignkey')
        batch_op.create_foreign_key(None, 'delivery_users', ['delivery_user_id'], ['id'])
        batch_op.drop_table_comment(
        'location_update_rooms',
        existing_comment='WebSocket namespace rooms for broadcasting real-time delivery locations to buyers and sellers',
        schema=None
    )

    with op.batch_alter_table('order_location_mappings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to the order being tracked',
               existing_nullable=False)
        batch_op.alter_column('room_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Socket.io room where location updates are broadcast',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('idx_order_location_mappings_order_id')
        batch_op.drop_index('idx_order_location_mappings_room_id')
        batch_op.drop_constraint('unique_order_room_mapping', type_='unique')
        batch_op.drop_constraint('fk_location_room_mapping', type_='foreignkey')
        batch_op.create_foreign_key(None, 'location_update_rooms', ['room_id'], ['room_id'])
        batch_op.drop_table_comment(
        'order_location_mappings',
        existing_comment='Maps orders to their associated location tracking rooms for real-time delivery tracking',
        schema=None
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_location_mappings', schema=None) as batch_op:
        batch_op.create_table_comment(
        'order_location_mappings',
        'Maps orders to their associated location tracking rooms for real-time delivery tracking',
        existing_comment=None,
        schema=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_location_room_mapping', 'location_update_rooms', ['room_id'], ['room_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_unique_constraint('unique_order_room_mapping', ['order_id', 'room_id'])
        batch_op.create_index('idx_order_location_mappings_room_id', ['room_id'], unique=False)
        batch_op.create_index('idx_order_location_mappings_order_id', ['order_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('room_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Socket.io room where location updates are broadcast',
               existing_nullable=False)
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               comment='Reference to the order being tracked',
               existing_nullable=False)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('location_update_rooms', schema=None) as batch_op:
        batch_op.create_table_comment(
        'location_update_rooms',
        'WebSocket namespace rooms for broadcasting real-time delivery locations to buyers and sellers',
        existing_comment=None,
        schema=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_delivery_user_rooms', 'delivery_users', ['delivery_user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_index('idx_location_update_rooms_room_id', ['room_id'], unique=False)
        batch_op.create_index('idx_location_update_rooms_delivery_user_id', ['delivery_user_id'], unique=False)
        batch_op.create_index('idx_location_update_rooms_created_at', [sa.text('created_at DESC')], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('delivery_user_id',
               existing_type=sa.INTEGER(),
               comment='Delivery partner assigned to this room (optional, can be NULL)',
               existing_nullable=True)
        batch_op.alter_column('room_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Socket.io room identifier (UUID format)',
               existing_nullable=False)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('delivery_users', schema=None) as batch_op:
        batch_op.create_table_comment(
        'delivery_users',
        'Stores delivery partner information and status',
        existing_comment=None,
        schema=None
    )
        batch_op.create_index('idx_delivery_users_status', ['status'], unique=False)
        batch_op.create_index('idx_delivery_users_phone_number', ['phone_number'], unique=False)
        batch_op.create_index('idx_delivery_users_email', ['email'], unique=False)
        batch_op.create_index('idx_delivery_users_created_at', ['created_at'], unique=False)
        batch_op.create_unique_constraint('delivery_users_phone_number_key', ['phone_number'])
        batch_op.create_unique_constraint('delivery_users_email_key', ['email'])
        batch_op.alter_column('rating',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('vehicle_type',
               existing_type=sa.Enum('BIKE', 'CAR', 'VAN', 'TRUCK', name='deliveryvehicletype'),
               type_=postgresql.ENUM('BIKE', 'CAR', 'VAN', 'TRUCK', name='delivery_vehicle_type'),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='deliverystatus'),
               type_=postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', name='delivery_status'),
               comment='Current status: ACTIVE for available, INACTIVE for disabled, SUSPENDED for temporary ban',
               existing_nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=15),
               comment='Used for OTP authentication during login',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='Unique identifier for delivery partner',
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('delivery_order_assignments', schema=None) as batch_op:
        batch_op.create_table_comment(
        'delivery_order_assignments',
        'Links orders to delivery partners and tracks the status of each assignment through the delivery lifecycle',
        existing_comment=None,
        schema=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_delivery_user_assignment', 'delivery_users', ['delivery_user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('fk_location_room_assignment', 'location_update_rooms', ['room_id'], ['room_id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_index('idx_delivery_order_assignments_status', ['status'], unique=False)
        batch_op.create_index('idx_delivery_order_assignments_room_id', ['room_id'], unique=False)
        batch_op.create_index('idx_delivery_order_assignments_order_id', ['order_id'], unique=False)
        batch_op.create_index('idx_delivery_order_assignments_logistical_status', ['logistical_status'], unique=False)
        batch_op.create_index('idx_delivery_order_assignments_delivery_user_id', ['delivery_user_id'], unique=False)
        batch_op.create_index('idx_delivery_order_assignments_assignment_id', ['assignment_id'], unique=False)
        batch_op.create_index('idx_delivery_order_assignments_assigned_at', [sa.text('assigned_at DESC')], unique=False)
        batch_op.alter_column('escrow_qr_code',
               existing_type=sa.VARCHAR(length=255),
               comment='QR code scanned by buyer to release escrow payment after delivery confirmation',
               existing_nullable=False)
        batch_op.alter_column('logistical_status',
               existing_type=sa.Enum('ARRIVED_PICKUP', 'PICKED_UP', 'EN_ROUTE_TO_DROPOFF', 'DELIVERED_PENDING_QR', name='logisticalstatus'),
               type_=postgresql.ENUM('ARRIVED_PICKUP', 'PICKED_UP', 'EN_ROUTE_TO_DROPOFF', 'DELIVERED_PENDING_QR', name='logistical_status'),
               comment='Delivery progress: ARRIVED_PICKUP -> PICKED_UP -> EN_ROUTE_TO_DROPOFF -> DELIVERED_PENDING_QR',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('ASSIGNED', 'ACCEPTED', 'REJECTED', name='assignmentstatus'),
               type_=postgresql.ENUM('ASSIGNED', 'ACCEPTED', 'REJECTED', name='assignment_status'),
               comment='Assignment status: ASSIGNED (awaiting response), ACCEPTED (partner accepted), REJECTED (partner declined)',
               existing_nullable=False)
        batch_op.alter_column('assigned_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('assignment_id',
               existing_type=sa.VARCHAR(length=36),
               comment='UUID for idempotent assignment creation (prevents duplicate assignments)',
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('delivery_last_locations', schema=None) as batch_op:
        batch_op.create_table_comment(
        'delivery_last_locations',
        'Stores the most recent GPS location of each delivery partner for tracking',
        existing_comment=None,
        schema=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_delivery_user_location', 'delivery_users', ['delivery_user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index('idx_delivery_last_locations_timestamp', [sa.text('timestamp DESC')], unique=False)
        batch_op.create_index('idx_delivery_last_locations_geo', ['latitude', 'longitude'], unique=False)
        batch_op.create_index('idx_delivery_last_locations_delivery_user_id', ['delivery_user_id'], unique=False)
        batch_op.alter_column('accuracy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GPS accuracy in meters (smaller is better)',
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               comment='When this location was recorded - use DESC index for getting latest',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    op.drop_table('chat_offers')
    with op.batch_alter_table('chat_message_reactions', schema=None) as batch_op:
        batch_op.drop_index('idx_chat_message_reaction_user')
        batch_op.drop_index('idx_chat_message_reaction_type')
        batch_op.drop_index('idx_chat_message_reaction_message')

    op.drop_table('chat_message_reactions')
    op.drop_table('chat_discounts')
    op.drop_table('product_inventory')
    op.drop_table('order_items')
    op.drop_table('chat_messages')
    op.drop_table('cart_items')
    op.drop_table('shipping_addresses')
    op.drop_table('shipments')
    op.drop_table('seller_offers')
    op.drop_table('product_views')
    op.drop_table('product_variants')
    op.drop_table('product_tags')
    op.drop_table('product_reviews')
    op.drop_table('product_images')
    op.drop_table('product_categories')
    op.drop_table('post_products')
    with op.batch_alter_table('post_comment_reactions', schema=None) as batch_op:
        batch_op.drop_index('idx_comment_reaction_user')
        batch_op.drop_index('idx_comment_reaction_type')
        batch_op.drop_index('idx_comment_reaction_comment')

    op.drop_table('post_comment_reactions')
    op.drop_table('payments')
    op.drop_table('chat_rooms')
    op.drop_table('transactions')
    op.drop_table('social_media_posts')
    op.drop_table('seller_categories')
    op.drop_table('request_images')
    op.drop_table('request_categories')
    op.drop_table('products')
    op.drop_table('post_likes')
    op.drop_table('post_comments')
    op.drop_table('post_categories')
    op.drop_table('orders')
    with op.batch_alter_table('niche_posts', schema=None) as batch_op:
        batch_op.drop_index('idx_niche_post_status')
        batch_op.drop_index('idx_niche_post_pinned')
        batch_op.drop_index('idx_niche_post_featured')

    op.drop_table('niche_posts')
    op.drop_table('media_variants')
    op.drop_table('carts')
    op.drop_table('user_settings')
    op.drop_table('user_addresses')
    op.drop_table('sellers')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('idx_user_posts')
        batch_op.drop_index('idx_post_search', postgresql_using='gin')

    op.drop_table('posts')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_notification_user_unread')
        batch_op.drop_index('idx_notification_user_type')

    op.drop_table('notifications')
    with op.batch_alter_table('niche_moderation_actions', schema=None) as batch_op:
        batch_op.drop_index('idx_moderation_type')
        batch_op.drop_index('idx_moderation_target')
        batch_op.drop_index('idx_moderation_niche')
        batch_op.drop_index('idx_moderation_active')

    op.drop_table('niche_moderation_actions')
    with op.batch_alter_table('niche_memberships', schema=None) as batch_op:
        batch_op.drop_index('idx_niche_membership_user')
        batch_op.drop_index('idx_niche_membership_role')
        batch_op.drop_index('idx_niche_membership_active')

    op.drop_table('niche_memberships')
    op.drop_table('niche_categories')
    op.drop_table('media')
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index('idx_followee_follower')

    op.drop_table('follows')
    op.drop_table('buyers')
    op.drop_table('buyer_requests')
    op.drop_table('users')
    op.drop_table('tags')
    with op.batch_alter_table('niches', schema=None) as batch_op:
        batch_op.drop_index('idx_niche_visibility')
        batch_op.drop_index('idx_niche_status')
        batch_op.drop_index('idx_niche_slug')

    op.drop_table('niches')
    op.drop_table('categories')
    # ### end Alembic commands ###
