"""feat(users): add is_active and deactivated_at to User and Buyer models

Revision ID: e364f9270d1c
Revises: d66e01aa5e2e
Create Date: 2025-07-14 17:22:44.089741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e364f9270d1c'
down_revision = 'd66e01aa5e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deactivated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deactivated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('deactivated_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.drop_column('deactivated_at')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
